FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-1

  install_script:
    - pkg install -y cmake gmake openal-soft png sdl2

  script:
    - mkdir build
    - cd build
    - cmake .. -DAQUARIA_INTERNAL_PNG=OFF -DAQUARIA_USE_SDL2=ON
    - make -j2

Linux_task:
  container:
    image: debian:testing-slim

  install_script:
    - apt update
    - apt install -y -q build-essential cmake libsdl2-dev libopenal-dev clang

  script:
    - mkdir build
    - cd build
    - cmake .. -DAQUARIA_USE_SDL2=ON
    - make -j2

  env:
    CC:  clang
    CXX: clang++


macOS_task:
  osx_instance:
    image: catalina-xcode

  install_script:
    - brew update
    - brew upgrade
    - brew install cmake llvm make openal-soft sdl2
    - brew info    cmake llvm make openal-soft sdl2

  script:
    - mkdir build
    - cd build
    - cmake .. -DAQUARIA_USE_SDL2=ON
    - make -j2

  env:
    CC:  clang
    CXX: clang++
