linux_task:
  container:
    image: debian:testing-slim

    install_script:
      - apt update
      - apt install build-essential cmake libsdl2-dev libopenal-dev

    script:
      - mkdir build
      - cd build
      - cmake .. -DAQUARIA_USE_SDL2=ON
      - make -j
