# http://docs.travis-ci.com/user/build-configuration/
language: cpp

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

#matrix:

#branches:
#  only:
#    - master

addons:
  apt:
    packages:
      - libopenal-dev
      - libsdl-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl openal-soft; fi

script:
# ALL THE BUILD COMMANDS HERE
  - export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;/usr/lib/x86_64-linux-gnu/"
  - CMAKE_OPTIONS='-DCMAKE_PREFIX_PATH='"$CMAKE_PREFIX_PATH"' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DAQUARIA_INTERNAL_FREETYPE=OFF -DAQUARIA_INTERNAL_LUA=OFF -DAQUARIA_INTERNAL_OGGVORBIS=OFF -DAQUARIA_INTERNAL_OPENAL=OFF -DAQUARIA_INTERNAL_PNG=OFF -DAQUARIA_INTERNAL_SDL=OFF -DAQUARIA_INTERNAL_TINYXML2=OFF -DAQUARIA_INTERNAL_ZLIB=OFF'
  - rm -rf cmake-build
  - mkdir cmake-build
  - cd cmake-build
  - cmake $CMAKE_OPTIONS ..
  - make -j 2

notifications:
  irc:
    channels:
      - "irc.esper.net#bitblot"
    skip_join: true
    use_notice: true
    on_success: change
    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      - "[%{repository_slug}#%{branch} @%{commit}] (%{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
