#ifndef __BBGE_COMPILE_CONFIG_H__
#define __BBGE_COMPILE_CONFIG_H__

#ifndef BBGE_SKIP_CONFIG_HEADERS

#define BBGE_BUILD_FRAMEBUFFER 1
#define BBGE_BUILD_SHADERS 1
#define BBGE_BUILD_OPENGL 1
#define BBGE_BUILD_OPENGL_DYNAMIC 1
#define BBGE_BUILD_FMOD_OPENAL_BRIDGE 1
#define BBGE_BUILD_ACHIEVEMENTS_INTERNAL 1
#define BBGE_BUILD_VFS 1
#define BBGE_BUILD_SDL2 1

#endif

#endif
