#ifndef BBGE_COMPILE_CONFIG_H
#define BBGE_COMPILE_CONFIG_H

#ifndef BBGE_SKIP_CONFIG_HEADERS

#define BBGE_BUILD_FMOD_OPENAL_BRIDGE 1
#define BBGE_BUILD_ACHIEVEMENTS_INTERNAL 1
#define BBGE_BUILD_VFS 1

#endif

#endif
